#ifndef TWI_MASTER_CONFIG_H
#define TWI_MASTER_CONFIG_H
#define I2C_SCL_PIN   1
#define I2C_SDA_PIN   7

#define TWI_MASTER_CONFIG_CLOCK_PIN_NUMBER I2C_SCL_PIN
#define TWI_MASTER_CONFIG_DATA_PIN_NUMBER I2C_SDA_PIN

#endif
